spring:
  application:
    name: springcloud-demo-gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: springcloud-demo-service1
          uri: lb://SPRINGCLOUD-DEMO-SERVICE1
          predicates:
            - Path=/svc1/**
          filters:
            - name: CircuitBreaker
              args:
                name: svc1CircuitBreaker
                fallbackUri: forward:/gateway/fallback
        - id: springcloud-demo-service2
          uri: lb://SPRINGCLOUD-DEMO-SERVICE2
          predicates:
            - Path=/svc2/**
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
management:
  # This is the property required to enable gateway.
  endpoint:
    gateway.enabled: true

  info:
    java.enabled: true
    env.enabled: true
  # Expose gateway web endpoint to get list of all
  # routes...
  # URLs to access: http://{host}/actuator/gateway/routes
  # Check more docs here: https://cloud.spring.io/spring-cloud-gateway/multi/multi__actuator_api.html
  endpoints.web:
    exposure.include: info,health,gateway
