spring:
  application:
    name: springcloud-demo-gateway
  cloud:
    gateway:
      routes:
        - id: springcloud-demo-service1
          uri: http://localhost:8081
          predicates:
            - Path=/svc1/**
        - id: springcloud-demo-service2
          uri: http://localhost:8082
          predicates:
            - Path=/svc2/**
server:
  port: 8080
  eureka:
    instance:
      hostname: localhost
