spring:
  application:
    name: springcloud-demo-gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: springcloud-demo-service1
          uri: lb://SPRINGCLOUD-DEMO-SERVICE1
          predicates:
            - Path=/svc1/**
          filters:
            - name: CircuitBreaker
              args:
                name: svc1CircuitBreaker
                fallbackUri: forward:/gateway/fallback
        - id: springcloud-demo-service2
          uri: lb://SPRINGCLOUD-DEMO-SERVICE2
          predicates:
            - Path=/svc2/**
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
management:
  endpoint:
    gateway.enabled: true
  endpoints:
    web.exposure.include: gateway
