server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Not recommended as this will simply logs everything onto console (Standard output) without
    # any optimizations of a logging framework. See: https://www.baeldung.com/sql-logging-spring-boot
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        # Not recommended as this will simply logs everything onto console (Standard output) without
        # any optimizations of a logging framework. See: https://www.baeldung.com/sql-logging-spring-boot
        format_sql: true
  h2:
    console.enabled: true