server:
  port: 8080

  # SpringBoot's ErrorController settings for handling exceptions...
  # See following for more details:
  #   1. https://reflectoring.io/spring-boot-exception-handling/
  #   2. https://www.baeldung.com/exception-handling-for-rest-with-spring#spring-boot for details...
  error:
    whitelabel.enabled: false
    #include-message: always
    include-binding-errors: always
    include-stacktrace: on_param # Add ?trace=true param while calling rest endpoints...
    include-exception: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        # Not recommended as this will simply logs everything onto console (Standard output) without
        # any optimizations of a logging framework. See: https://www.baeldung.com/sql-logging-spring-boot
        format_sql: true
    # Not recommended as this will simply logs everything onto console (Standard output) without
    # any optimizations of a logging framework. See: https://www.baeldung.com/sql-logging-spring-boot
    show-sql: true
  h2:
    console.enabled: true
logging:
  level:
    # Ref: https://www.baeldung.com/sql-logging-spring-boot
    # Log SQL queries
    org.hibernate.SQL: DEBUG
    # Log query binding parameters...
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    venkat.springboot.simple.jpademo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n"