# See JPADemoApplication class on how this profile is getting loaded programatically.
#        SpringApplication application = new SpringApplication(JpaDemoApplication.class);
#        application.setAdditionalProfiles(SecurityConstants.SECURITY_PROFILE_NAME);
#        application.run(args);
spring:
  # Donot exclude complete security autoconfiguration... See https://www.baeldung.com/spring-boot-security-autoconfiguration
  # autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  security:
    user:
      #name: user
      password: venkat
app.security:
  config: AppBasicSecurityConfig
  enabled: true
  permit-urls: /h2-console/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html

# For swagger to work...
springdoc.swagger-ui:
  csrf:
    enabled: true
logging:
  level:
    org.springframework.security.web: DEBUG