INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY, PRICE) VALUES (1, 'Book 1', 'Author 1', 'ISBN1', 'SCIENTIFIC', 399.99);
INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY, PRICE) VALUES (2, 'Book 2', 'Author 1', 'ISBN2', 'SCIENTIFIC', 29.99);
INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY, PRICE) VALUES (3, 'Book 3', 'Author 2', 'ISBN3', 'FICTION', 99.99);