INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY) VALUES (1, 'Book 1', 'Author 1', 'ISBN1', 'SCIENTIFIC');
INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY) VALUES (2, 'Book 2', 'Author 1', 'ISBN2', 'SCIENTIFIC');
INSERT INTO BOOK (ID, TITLE, AUTHOR, ISBN, CATEGORY) VALUES (3, 'Book 3', 'Author 2', 'ISBN3', 'FICTIONAL');