spring:
  application:
    name: springcloud-demo-gateway-autodiscovery
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #lower-case-service-id: true
      # After hitting the gateway a few times, see metrics in URL: http://{host}/metrics and Sub URLs...
      metrics.enabled: true
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
management:
  endpoint:
    # This is the property required to enable gateway.
    gateway.enabled: true
    health:
      show-details: always
  endpoints:
    web.exposure.include: info,health,gateway
