spring:
  application.name: springcloud-demo-service2
server:
  port: ${server2port:8082}
eureka:
  instance:
    hostname: localhost
management:
  info:
    java.enabled: true
    env.enabled: true
  endpoints.web:
    exposure.include: health,info