app:
  redis:
    host: localhost
    port: 6379
    password: falcon123
    db: 0
    connection-pool-config:
      minimum-idle: 5
      maximum-idle: 8
      maximum-connection: 350
      timeout-minutes: 3

