server.port: 8081
spring.cloud.config.server.native.searchLocations: classpath:/config
# spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/venkatbabukr/SpringBoot
#          basedir: springcloud-config-server/src/main/resources/config
#          default-label: main