server.port: 8081
spring.cloud.config.server.native.searchLocations: classpath:/config/{application}
#spring.cloud.config.server.git:
#  uri: https://github.com/venkatbabukr/SpringBoot
#  search-paths:
#    - /springcloud-config-server/src/main/resources/config