spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: library
      uri: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: health,refresh